import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Nav from "./components/NavBar/nav";
import Provider from "../app/components/provider";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={manrope.className}>
				<main>
					<Provider>
						<Nav />
						{children}
					</Provider>
				</main>
			</body>
		</html>
	);
}
